version: avb{build}

os: Visual Studio 2015

init:
  - ps: >-
      if ($env:appveyor_repo_tag -eq "true") {
        Update-AppveyorBuild -Version "$env:appveyor_repo_tag_name"
      } else {
        Update-AppveyorBuild -Version "dev-$($env:appveyor_repo_commit.substring(0,7))"
      }

environment:
  global:
    PLATFORMTOOLSET: v140
    BITS: 32
  matrix:
    - CONFIGURATION: Debug
      COMPILER: MSVC15
      PLATFORM: x86_32
    - CONFIGURATION: Debug
      COMPILER: MSVC15
      PLATFORM: x86_64
    - CONFIGURATION: Release
      COMPILER: MSVC15
      PLATFORM: x86_32
    - CONFIGURATION: Release
      COMPILER: MSVC15
      PLATFORM: x86_64
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: i686
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: x86_64

build:
  project: rufus.sln
  parallel: true
  verbosity: detailed

install:
- if [%COMPILER%]==[MinGW] xcopy /SQ C:\projects\rufus C:\msys64\home\appveyor\
- if [%PLATFORM%]==[x86_64] set BITS=64

build_script:
- if [%COMPILER%]==[MSVC15] msbuild rufus.sln /m /p:Configuration=%CONFIGURATION%,Platform=%PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- if [%COMPILER%]==[MinGW] C:\msys64\usr\bin\bash -lc "export PATH=/mingw%BITS%/bin:$PATH; ./configure --build=%PLATFORM%-w64-mingw32 --host=%PLATFORM%-w64-mingw32 --disable-debug; make -j4"
